### PR TITLE
Add .all function to return array of all rotations

### PR DESCRIPTION
**Pull request by dsernst**
This adds an additional `.all` function, with jshint compliant code, a unit test, and usage documentation:

> ## rotate.all(array)
> 
> Returns all rotations for the given array. It does not modify the passed in array.
> 
> Example:
> 
> ``` js
> var beatles = ['paul', 'john', 'ringo', 'george'];
> console.log(rotate.all(beatles));
> // [ [ 'paul', 'john', 'ringo', 'george' ],
> //   [ 'john', 'ringo', 'george', 'paul' ],
> //   [ 'ringo', 'george', 'paul', 'john' ],
> //   [ 'george', 'paul', 'john', 'ringo' ] ]
> ```

### CODE REVIEW

**Comment by dsernst** [comment]
This failing CI test https://travis-ci.org/CMTegner/rotate-array/jobs/78308042 looks like a problem with outdated dependencies. It never gets past `npm install`

**Comment by CMTegner** [comment]
If you rebase against master the tests should pass. I'd appreciate if you removed the `.gitignore` commit. Everyone has their own preference when it comes to files they want to ignore (editors, IDEs, etc), so I find it reduces friction if contributors make their own, local ignore rules. Mine tends to look like this:

```
node_modules
.gitignore
```

**Comment by dsernst** [comment]
Done :+1:

**Comment by CMTegner** [comment]
Pushed to npm in 1.1.0. I forgot to mention this before I merged the PR, but it's usually better to let the repo maintainer adjust the version number. The version number will usually be bumped right before publishing to npm, so doing it in individual PRs may not be desirable.

**Comment by dsernst** [comment]
Good point :+1:

On Saturday, January 2, 2016, Christian Maughan Tegnér <
notifications@github.com> wrote:

> Pushed to npm in 1.1.0. I forgot to mention this before I merged the PR,
> but it's usually better to let the repo maintainer adjust the version
> number. The version number will usually be bumped right before publishing
> to npm, so doing it in individual PRs may not be desirable.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CMTegner/rotate-array/pull/1#issuecomment-168394399.

## 

## 

David Ernst

**Pull request merged**
